workspace = { members = ["crates/game", "crates/rng"] }
[package]
name = "schafkopf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
